language: php

php:
  - 5.5
  - 5.6

addons:
  apt:
    packages:
      - libyaml-dev

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update


script:
  - composer install --dev
  - vendor/phpunit/phpunit/phpunit tests/
