language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - printf "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer install
  - phpunit tests/
