language: php

php:
  - 5.5

before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)
  - composer self-update

addons:
  apt:
    packages:
      - libyaml-dev
script:
  - composer install --dev
  - vendor/phpunit/phpunit/phpunit tests/
